### ISSUE TITLE
Switched remotes or READMEs?

### ISSUE THREAD

**Issue by almereyda** [joshuabenuck/wiki-plugin-specs#1]
The README of this repository talks about https://github.com/joshuabenuck/wiki-plugin-compare

Does this mean the repositories are switched, or only the READMEs?

**Comment by joshuabenuck** [comment]
Good catch. I mixed up the remotes when I first checked in the projects and later corrected the remotes, but missed the readmes.

A word of warning: Neither plugin is really ready for much use just yet. If you have a use case in mind, I'd love to hear about it.
